PronosticadorFutbol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('emailmarketing.urls')),
    path('administrator/', include('administrator.urls')),
    path('pages/', include('pages.urls')),
    path('feeder/', include('feeder.urls')),
    path('forecasts/', include('forecasts.urls')),
    path('payment/', include('payment.urls')),
    # paths de Auth. con este path django nos provee de varias urls para manejar autenticacion
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('summernote/', include('django_summernote.urls')),
    
]
if settings.DEBUG:
    from django.conf.urls.static import static
    # variables MEDIA_URL Y MEDIA_ROOT las tenemos que declarar en el settings del proyecto
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView, AboutView, contact

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact/', contact, name="contact"),
]

emailmarketing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #urls de emailmarketing
    
    path('subscribers/create', views.SubscriberCreateView.as_view(), name='subscriber-create'),
    path('subscribers/create-direct/', views.subscriberView, name='subscriber-create-direct'),
    path('subscribers/maintenance/', views.SubscriberListView.as_view(), name='subscribers-list'),
    path('subscribers/maintenance/create/', views.LoginSubscriberCreateView.as_view(), name='subscriber-maintenance-create'),
    path('subscribers/maintenance/update/<int:pk>/', views.SubscriberUpdateView.as_view(), name='subscriber-update'),
    path('subscribers/maintenance/delete/<int:pk>/', views.SubscriberDeleteView.as_view(), name='subscriber-delete'),
    path('subscribers/campaign/', views.emailMarketing, name='campaign-email-form'),

]

emailmarketing/models.py
from django.db import models

# Create your models here.

class Subscriber(models.Model):
    email = models.EmailField(max_length=100, verbose_name='Email')

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'
        ordering = ['email']
        
    
    def __str__(self):
        return self.email

emailmarketing/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from .models import Subscriber

class SuscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = '__all__'
        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder': 'Email'})
            
        }
        labels = {
            'email':''
        }

class EmailMarketingForm(forms.Form):

    subject = forms.CharField(label='', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Escribe el asunto'}
    ), max_length=100)
    message = forms.CharField(label='Mensaje', required=True, widget=SummernoteWidget(
        attrs={'class': 'form-control'}
    ), min_length=10, max_length=1000)

emailmarketing/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.http import Http404, JsonResponse
from .models import Subscriber
from .forms import SuscriberForm, EmailMarketingForm

# Create your views here.

# vista pública para suscribirse a la newsletter
class SubscriberCreateView(SuccessMessageMixin, CreateView):
    model = Subscriber
    form_class = SuscriberForm
    template_name = 'emailmarketing/subscriber_form.html'
    success_message = "Gracias por suscribirte a nuestra newsletter"
    success_url = reverse_lazy('home')


def subscriberView(request):
    json_response = {'created': False}
    
    email = request.GET.get('email')
    
    if email != '':
        if not Subscriber.objects.filter(email=email):
            suscriber = Subscriber(email=email)
            suscriber.save()
            json_response['created'] = True
            json_response['message'] = 'Gracias por subscribirte a la newsletter'
        else:
            json_response['message'] = 'El email introducido ya existe para otro usuario'
    else:
        json_response['message'] = 'Introduce un email'
    return JsonResponse(json_response)
    

# vista privada para listar los suscritores de la newsletter
@method_decorator(staff_member_required, name='dispatch')
class SubscriberListView(ListView):
    model = Subscriber
    template_name = 'emailmarketing/subscribers_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de suscriptores'
        return context

# vista para crear suscriptores desde login
# vista privada para suscribirse a la newsletter
@method_decorator(staff_member_required, name='dispatch')
class LoginSubscriberCreateView(CreateView):
    model = Subscriber
    form_class = SuscriberForm
    template_name = 'emailmarketing/subscriber_maintenance_form.html'
    success_url = reverse_lazy('subscribers-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Nuevo Suscriptor'
        return context


# vista para editar un paciente
@method_decorator(staff_member_required, name='dispatch')
class SubscriberUpdateView(UpdateView):
    model = Subscriber
    form_class = SuscriberForm
    template_name = 'emailmarketing/subscriber_form.html'
    success_url = reverse_lazy('subscribers-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Suscriptor'
        return context

# vista para eliminar un paciente
@method_decorator(staff_member_required, name='dispatch')
class SubscriberDeleteView(DeleteView):
    model = Subscriber
    template_name = 'emailmarketing/subscriber_confirm_delete.html'
    success_url = reverse_lazy('subscribers-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar Suscriptor'
        return context

# vista para la campaña de email marketing
# ver https://docs.djangoproject.com/en/5.1/topics/auth/default/
@staff_member_required
def emailMarketing(request):

    title = 'Campaña Email Marketing'
    contact_form = EmailMarketingForm()

    if request.method == 'POST':
        contact_form = EmailMarketingForm(data=request.POST)
        if contact_form.is_valid():
            subject = request.POST.get('subject', '')
            message = request.POST.get('message', '')
            
            # obtenemos los emails de todos los suscriptores

            subscribers = Subscriber.objects.all()
            
            
            # Enviamos el correo y redireccionamos

            for subscriber in subscribers:

                email = EmailMessage(
                    "Clínica Psicología: Campaña de Email Marketing",
                    "Asunto {} \n\nEscribió:\n\n{}".format(subject, message),
                    "no-contestar@pronosticos-futbol.com",
                    [subscriber.email],
                    #reply_to=[subscriber.email]
                )
                try:
                    email.send()
                    # Todo ha ido bien y rediccionamos a ok
                    #return redirect(reverse('campaign-email-form') + "?ok")
                except:
                    # algo no ha ido bien y rediccionamos a FAIL
                    
                    return redirect(reverse('subscribers-list') + "?fail")
            return redirect(reverse('subscribers-list') + "?ok")
        
    return render(request, 'emailmarketing/send_email_everyone.html', {
        'title': title,
        'form': contact_form
    })
    

emailmarketing/templates/emailmarketing/send_email_everyone.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
        <h2>{{title}}</h2> 
    </div><!-- End Section Title -->
    <div class="container">
      <div class="row gy-4">
        <!-- Formulario de contacto -->
        <div class="col-md-8">
          <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
              <!-- Formulario -->
              {{ form.as_p }}
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Enviar">
          </form>
        </div>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

emailmarketing/templates/emailmarketing/subscriber_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Suscriptor{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
      <h2>Eliminar Suscriptor</h2>      
    </div><!-- End Section Title -->
    <div class="container">
      <div class="row gy-4">
        <form method="post">{% csrf_token %}
            <p>¿Seguro que quieres eliminar el email <b>"{{object.email}}"</b>?</p>
            
            <input type="submit" value="Confirmar" class="btn btn-success">
            <a href="{% url 'subscribers-list' %}" class="btn btn-danger">Cancelar</a> 
        </form>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

emailmarketing/templates/emailmarketing/subscriber_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Suscriptores{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
        <h2 class='mb-3 mt-3'>Déjanos tu email y te enviaremos noticias acerca de Estratebet - Versión 1.0</h2> 
    </div><!-- End Section Title -->
    <div class="container">
      <div class="row gy-4">
        <div class="col-md-8">
          <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary btn-block mt-3" value="Enviar">
            
          </form>
        </div>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

emailmarketing/templates/emailmarketing/subscriber_maintenance_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
        <h2>{{title}}</h2> 
    </div><!-- End Section Title -->
    <div class="container">
      <div class="row gy-4">
        <div class="col-md-8">
          <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
              <!-- Formulario -->
              {{ form.as_p }}
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Enviar">
              
          </form>
        </div>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

emailmarketing/templates/emailmarketing/subscribers_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
      <h2>{{title}}</h2>
    </div><!-- End Section Title -->

    <div class="container text-center">
      <div class="row ">
        {% if 'ok' in request.GET %}
            <p><b>Campaña enviada correctamente</b></p>
        {% endif %}
        <div class="col">
          <a href="{% url 'subscriber-maintenance-create' %}" class="btn btn-light">
            <img src="{% static 'core/img/nuevo.png' %}" class="img-fluid" title='Nuevo suscriptor' width=40px height=40px alt="Nuevo suscriptor">
          </a>
          <a href="{% url 'campaign-email-form' %}" class="btn btn-light">
            <img src="{% static 'core/img/newsletter.png' %}" class="img-fluid" title='Nueva campaña' width=40px height=40px alt="Nueva campaña">
          </a>
        </div>
      </div>
    </div>

    <div class="container mt-5">
      <div class="row gy-4">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Email</th>
              <th scope="col">Acción</th>
            </tr>
          </thead> 
          <tbody>
            {% for subscriber in subscriber_list %}
              <tr>
                <td>{{subscriber.email}}</td>
                <td>                      
                  <a href="{% url 'subscriber-update' subscriber.id %}" class="btn btn-light">
                    <img src="{% static 'core/img/editar.png' %}" class="img-fluid" title='Editar suscriptor' width=25px height=20px alt="Editar">
                  </a>
                  <a href="{% url 'subscriber-delete' subscriber.id %}" class="btn btn-light">
                    <img src="{% static 'core/img/papelera.png' %}" class="img-fluid" title='Eliminar suscriptor' width=25px height=20px alt="Eliminar">
                  </a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}