PronosticadorFutbol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('emailmarketing.urls')),
    path('administrator/', include('administrator.urls')),
    path('pages/', include('pages.urls')),
    path('feeder/', include('feeder.urls')),
    path('forecasts/', include('forecasts.urls')),
    path('payment/', include('payment.urls')),
    # paths de Auth. con este path django nos provee de varias urls para manejar autenticacion
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('summernote/', include('django_summernote.urls')),
    
]
if settings.DEBUG:
    from django.conf.urls.static import static
    # variables MEDIA_URL Y MEDIA_ROOT las tenemos que declarar en el settings del proyecto
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView, AboutView, contact

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact/', contact, name="contact"),
]

feeder/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('contry/', views.ContriesListView.as_view(), name="contry-list"),
    path('contry/create', views.ContryCreateView.as_view(), name="contry-create"),
    path('league/', views.LeaguesListView.as_view(), name="league-list"),
    path('league/contry/<int:pk>', views.LeaguesByContryListView.as_view(), name="league-contry-list"),
    path('league/create', views.LeagueCreateView.as_view(), name="league-create"),
    path('team/league/<int:pk>', views.TeamByLeagueListView.as_view(), name="team-league-list"),
    path('team/create', views.TeamCreateView.as_view(), name="team-create"),
    path('match/team/<int:pk>', views.MatchesByTeamListView.as_view(), name="matches-team-list"),
    path('scraper/update-score', views.scraper_resultados, name="scraper-score"),
    path('scraper/create-league', views.scraper_create_teams, name="scraper-create-league"),
    path('scraper/create-matches', views.scraper_create_matches, name="scraper-create-matches"),
    
]

forecasts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here. 
# year.strftime('%Y')
#{{ year|date: "Y" }}
# modelo temporada
class Season(models.Model):
    season = models.DateField(verbose_name='Temporada')

    class Meta:
        verbose_name = 'Temporada'
        verbose_name_plural = 'Temporadas'

    def __str__(self):
        return self.season.strftime('%Y')

class Contry(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre')
    image = models.ImageField(verbose_name='Imagen', upload_to='contry', null=True, blank=True)

    class Meta:
        verbose_name = 'Pais'
        verbose_name_plural = 'Paises'
        
    def __str__(self):
        return self.name

class League(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')
    season = models.ForeignKey(Season, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Temporada')
    contry = models.ForeignKey(Contry, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Pais')
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name = 'Liga'
        verbose_name_plural = 'Ligas'
        ordering = ['name']
        
    
    def __str__(self):
        return self.name

class Team(models.Model):
    team = models.CharField(max_length=50, verbose_name='Equipo')
    league = models.ForeignKey(League, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Liga')
    image = models.ImageField(verbose_name='Imagen', upload_to='team')
    class Meta:
        verbose_name = 'Equipo'
        verbose_name_plural = 'Equipos'
        ordering = ['team']
        
    
    def __str__(self):
        return self.team


class Match(models.Model):
    league = models.ForeignKey(League, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Liga')
    soccer_day = models.SmallIntegerField(verbose_name='Jornada', null=True, blank=True)
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Equipo local',related_name='home_matches')
    visit_team = models.ForeignKey(Team, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Equipo visitante',related_name='visit_matches')
    date = models.DateField(verbose_name='Fecha')
    gol_home_ht = models.IntegerField(verbose_name='Goles Equipo Local HT', blank=True, null=True)
    gol_visit_ht = models.IntegerField(verbose_name='Goles Equipo Visitante HT', blank=True, null=True)
    gol_home_ft = models.IntegerField(verbose_name='Goles Equipo Local FT', blank=True, null=True)
    gol_visit_ft = models.IntegerField(verbose_name='Goles Equipo Visitante FT', blank=True, null=True)
    goles_tramo_1_10 = models.IntegerField(verbose_name='Goles del 1 al 10', blank=True, null=True)
    goles_tramo_11_20 = models.IntegerField(verbose_name='Goles del 11 al 20', blank=True, null=True)
    goles_tramo_21_30 = models.IntegerField(verbose_name='Goles del 21 al 30', blank=True, null=True)
    goles_tramo_31_40 = models.IntegerField(verbose_name='Goles del 31 al 40', blank=True, null=True)
    goles_tramo_41_50 = models.IntegerField(verbose_name='Goles del 41 al 50', blank=True, null=True)
    goles_tramo_51_60 = models.IntegerField(verbose_name='Goles del 51 al 60', blank=True, null=True)
    goles_tramo_61_70 = models.IntegerField(verbose_name='Goles del 61 al 70', blank=True, null=True)
    goles_tramo_71_80 = models.IntegerField(verbose_name='Goles del 71 al 80', blank=True, null=True)
    goles_tramo_81_90 = models.IntegerField(verbose_name='Goles del 81 al 90', blank=True, null=True)
    goles_tramo_91_final = models.IntegerField(verbose_name='Goles del 91 al final', blank=True, null=True)
    

    class Meta:
        verbose_name = 'Partido'
        verbose_name_plural = 'Partidos'
        ordering = ['date']
        
    
    def __str__(self):
        return '{} {}'.format(self.home_team, self.visit_team)


class Strategy(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuario')
    valor_ini_over_05_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_05_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_15_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_15_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_05_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_05_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_15_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_15_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_25_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_25_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_aem = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_aem = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_favorito = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_favorito = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_favorito = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_favorito = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = 'Estrategia'
        verbose_name_plural = 'Estrategias'
        
    def __str__(self):
        return self.name

feeder/forms.py
from django import forms
from forecasts.models import Contry, League, Team

class ContryForm(forms.ModelForm):
    
    class Meta:
        model = Contry
        fields = '__all__'
        
        
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nombre'}),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control-file mt-3'})
        }
        
        labels = {
            'name':'', 
            'image':'Bandera del pais'
        }


class LeagueForm(forms.ModelForm):
    
    class Meta:
        model = League
        fields = '__all__'
        
        
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nombre'}),
            'season': forms.Select(attrs={'class':'form-control'}),
            'contry': forms.Select(attrs={'class':'form-control'}),
        }
        
        labels = {
            'name':'', 
            'season':'Temporada',
            'contry': 'Pais'
        }


class TeamForm(forms.ModelForm):
    
    class Meta:
        model = Team
        fields = '__all__'
        
        
        widgets = {
            'team': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nombre del equipo'}),
            'league': forms.Select(attrs={'class':'form-control'}),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control-file mt-3'})
        }
        
        labels = {
            'team':'', 
            'league':'Liga',
            'image': 'Escudo'
        }

feeder/templates/feeder/contries_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-8">
      <h1>{{title}}</h1>
      {% if request.user.is_staff %}
        <div class="container text-center">
          <div class="row ">
            <div class="col mb-5">
              <a href="{% url 'contry-create' %}" class="btn btn-success" id="btn-update-professional">Nuevo Pais</a>
            </div>
          </div>
        </div>
      {% endif %}

      <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Bandera</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead> 
            <tbody>
              {% for contry in contry_list %}
                  <tr>
                    <td>{{contry.name}}</td>
                    <td><img src="{{contry.image.url}}" alt="" class="img-fluid" width='40px' height='40px'></td>
                    
                    <td>                      
                      <a href="{% url 'league-contry-list' contry.id %}" class="btn btn-primary">Ligas</a>
                    </td>
                  </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

feeder/templates/feeder/contry_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
      <h1>{{title}}</h1>

      <!-- Content Row -->
      <div class="row">
          <!-- Earnings (Monthly) Card Example -->
          
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <!-- Formulario -->
            <!--
            <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar">
            -->
            {{ form.as_p }}
            
            <input type="submit" class="btn btn-primary btn-block mt-3" value="Crear">
        </form>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

feeder/templates/feeder/league_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
      <h1>{{title}}</h1>

      <!-- Content Row -->
      <div class="row">
          <!-- Earnings (Monthly) Card Example -->
          
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <!-- Formulario -->
            <!--
            <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar">
            -->
            {{ form.as_p }}
            
            <input type="submit" class="btn btn-primary btn-block mt-3" value="Crear">
        </form>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

feeder/templates/feeder/leagues_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-8">
      <h1>{{title}}</h1>
      {% if request.user.is_staff %}
        <div class="container text-center">
          <div class="row ">
            <div class="col mb-5">
              <a href="{% url 'league-create' %}" class="btn btn-success" id="btn-update-professional">Nueva Liga</a>
            </div>
          </div>
        </div>
      {% endif %}

      <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                  <th scope="col">Bandera</th>
                  <th scope="col">Pais</th>
                  <th scope="col">Nombre</th>
                  <th scope="col">Temporada</th>
                  <th scope="col">Acción</th>
                    
                </tr>
            </thead> 
            <tbody>
              {% for league in league_list %}
                  <tr>
                    <td><img src="{{league.contry.image.url}}" alt="" class="img-fluid" width='40px' height='40px'></td>                    
                    <td>{{league.contry}}</td>
                    <td>{{league.name}}</td>
                    <td>{{league.season}}</td>                    
                    <td>                      
                      <a href="{% url 'team-league-list' league.id %}" class="btn btn-primary">Equipos</a>
                    </td>
                  </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

feeder/templates/feeder/scraper.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
      <h1>{{title}}</h1>

      <div class="container text-center">
        <div class="row">

        </div>
    </div>
</div>
{% endblock %}

feeder/templates/feeder/scraper_create_league.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
      <h1>{{title}}</h1>

      <div class="container text-center">
        <div class="row">

        </div>
    </div>
</div>
{% endblock %}

feeder/templates/feeder/scraper_create_matches.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
      <h1>{{title}}</h1>

      <div class="container text-center">
        <div class="row">

        </div>
    </div>
</div>
{% endblock %}

feeder/templates/feeder/scraper_score.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
      <h1>{{title}}</h1>

      <div class="container text-center">
        <div class="row">

        </div>
    </div>
</div>
{% endblock %}

feeder/templates/feeder/team_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
      <h1>{{title}}</h1>

      <!-- Content Row -->
      <div class="row">
          <!-- Earnings (Monthly) Card Example -->
          
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <!-- Formulario -->
            <!--
            <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar">
            -->
            {{ form.as_p }}
            
            <input type="submit" class="btn btn-primary btn-block mt-3" value="Crear">
        </form>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

feeder/templates/feeder/teams_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-8">
      <h1>{{title}}</h1>
      {% if request.user.is_staff %}
      <div class="container text-center">
        <div class="row ">
          <div class="col mb-5">
            <a href="{% url 'team-create' %}" class="btn btn-success" id="btn-update-professional">Nuevo Equipo</a>
          </div>
        </div>
      </div>
      {% endif %}
      <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                  <th scope="col">Escudo</th>
                  <th scope="col">Nombre</th>
                  <th scope="col">Liga</th>
                  <th scope="col">Acción</th>
                </tr>
            </thead> 
            <tbody>
              {% for team in team_list %}
                  <tr>
                    <td><img src="{{team.image.url}}" alt="" class="img-fluid" width='40px' height='40px'></td>                    
                    <td>{{team.team}}</td>
                    <td>{{team.league}}</td>
                    <td>
                      <a href="{% url 'matches-team-list' team.id %}" class="btn btn-primary">Partidos</a>
                    </td>
                  </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}