PronosticadorFutbol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('emailmarketing.urls')),
    path('administrator/', include('administrator.urls')),
    path('pages/', include('pages.urls')),
    path('feeder/', include('feeder.urls')),
    path('forecasts/', include('forecasts.urls')),
    path('payment/', include('payment.urls')),
    # paths de Auth. con este path django nos provee de varias urls para manejar autenticacion
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('summernote/', include('django_summernote.urls')),
    
]
if settings.DEBUG:
    from django.conf.urls.static import static
    # variables MEDIA_URL Y MEDIA_ROOT las tenemos que declarar en el settings del proyecto
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView, AboutView, contact

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact/', contact, name="contact"),
]

forecasts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('<int:pk>/', views.NextMatchesListView.as_view(), name="next-matchs-list"),
    path('match/<int:pk>/', views.MatchDetailView.as_view(), name="match-detail"),
    path('match/live/<int:pk>/', views.updateLive, name="update-live"),
    path('matches/', views.MatchesbyleaguesDate, name="matches-leagues-date-list"),
    path('strategy/', views.StrategyCreateView.as_view(), name="strategy-create"),
    path('strategy/list/', views.StrategiesListView.as_view(), name="strategies-list"),
    path('strategy/update/<int:pk>/', views.StrategyUpdateView.as_view(), name='strategy-update'),
    path('strategy/delete/<int:pk>/', views.StrategyDeleteView.as_view(), name='strategy-delete')
]

forecasts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here. 
# year.strftime('%Y')
#{{ year|date: "Y" }}
# modelo temporada
class Season(models.Model):
    season = models.DateField(verbose_name='Temporada')

    class Meta:
        verbose_name = 'Temporada'
        verbose_name_plural = 'Temporadas'

    def __str__(self):
        return self.season.strftime('%Y')

class Contry(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre')
    image = models.ImageField(verbose_name='Imagen', upload_to='contry', null=True, blank=True)

    class Meta:
        verbose_name = 'Pais'
        verbose_name_plural = 'Paises'
        
    def __str__(self):
        return self.name

class League(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')
    season = models.ForeignKey(Season, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Temporada')
    contry = models.ForeignKey(Contry, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Pais')
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name = 'Liga'
        verbose_name_plural = 'Ligas'
        ordering = ['name']
        
    
    def __str__(self):
        return self.name

class Team(models.Model):
    team = models.CharField(max_length=50, verbose_name='Equipo')
    league = models.ForeignKey(League, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Liga')
    image = models.ImageField(verbose_name='Imagen', upload_to='team')
    class Meta:
        verbose_name = 'Equipo'
        verbose_name_plural = 'Equipos'
        ordering = ['team']
        
    
    def __str__(self):
        return self.team


class Match(models.Model):
    league = models.ForeignKey(League, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Liga')
    soccer_day = models.SmallIntegerField(verbose_name='Jornada', null=True, blank=True)
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Equipo local',related_name='home_matches')
    visit_team = models.ForeignKey(Team, on_delete=models.CASCADE, blank=False, null=False, verbose_name='Equipo visitante',related_name='visit_matches')
    date = models.DateField(verbose_name='Fecha')
    gol_home_ht = models.IntegerField(verbose_name='Goles Equipo Local HT', blank=True, null=True)
    gol_visit_ht = models.IntegerField(verbose_name='Goles Equipo Visitante HT', blank=True, null=True)
    gol_home_ft = models.IntegerField(verbose_name='Goles Equipo Local FT', blank=True, null=True)
    gol_visit_ft = models.IntegerField(verbose_name='Goles Equipo Visitante FT', blank=True, null=True)
    goles_tramo_1_10 = models.IntegerField(verbose_name='Goles del 1 al 10', blank=True, null=True)
    goles_tramo_11_20 = models.IntegerField(verbose_name='Goles del 11 al 20', blank=True, null=True)
    goles_tramo_21_30 = models.IntegerField(verbose_name='Goles del 21 al 30', blank=True, null=True)
    goles_tramo_31_40 = models.IntegerField(verbose_name='Goles del 31 al 40', blank=True, null=True)
    goles_tramo_41_50 = models.IntegerField(verbose_name='Goles del 41 al 50', blank=True, null=True)
    goles_tramo_51_60 = models.IntegerField(verbose_name='Goles del 51 al 60', blank=True, null=True)
    goles_tramo_61_70 = models.IntegerField(verbose_name='Goles del 61 al 70', blank=True, null=True)
    goles_tramo_71_80 = models.IntegerField(verbose_name='Goles del 71 al 80', blank=True, null=True)
    goles_tramo_81_90 = models.IntegerField(verbose_name='Goles del 81 al 90', blank=True, null=True)
    goles_tramo_91_final = models.IntegerField(verbose_name='Goles del 91 al final', blank=True, null=True)
    

    class Meta:
        verbose_name = 'Partido'
        verbose_name_plural = 'Partidos'
        ordering = ['date']
        
    
    def __str__(self):
        return '{} {}'.format(self.home_team, self.visit_team)


class Strategy(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuario')
    valor_ini_over_05_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_05_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_15_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_15_ht = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_05_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_05_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_15_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_15_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_over_25_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_over_25_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_aem = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_aem = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_anota_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_anota_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_anota_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_concede_ft = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_concede_mitad_1 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_concede_mitad_2 = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_local_favorito = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_local_favorito = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_ini_visitante_favorito = models.PositiveSmallIntegerField(null=True, blank=True)
    valor_fin_visitante_favorito = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = 'Estrategia'
        verbose_name_plural = 'Estrategias'
        
    def __str__(self):
        return self.name

forecasts/templates/forecasts/matches_leagues_date_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Content Row -->
  
  <div class="row justify-content-center">
    <div class="col-md-12 text-center mb-3 mt-3">
      <h1 class='mb-3 mt-4 mb-4'>{{title}}</h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                {{ form.leagues }}
              </div>
            </div>
            
            <div class="col-md-3">
              <div class="form-group">
                {{ form.start_date }}
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-group">
                {{ form.end_date }}
              </div>              
            </div>
            <div class="col-md-8 mb-3">
              <label for="">Selecciona una Estrategia</label>
              {{form.strategies}}
            </div>
            <div class="col-md-8 mb-3">
              <button type="submit" class="btn btn-primary" id="btn-filtrar">Filtrar</button>
            </div>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-12"> 
      {% if matches %}
        <div class="table-responsive">
          <table class="table mt-3">
            <thead>
              <tr>
                <th scope="col">Pais</th>
                <th scope="col">Liga</th>
                <th scope="col">Jornada</th>
                <th scope="col">Fecha</th>
                <th scope="col">Local</th>
                <th scope="col">Visitante</th>
                <th scope="col">Acción</th>
              </tr>
            </thead> 
            <tbody>
              {% for match in matches %}
                <tr>
                  <td><img src="{{match.league.contry.image.url}}" class="img-fluid" width=25px height=20px alt=""> </td>
                  <td>{{match.league}}</td>
                  <td>{{match.soccer_day}}</td>
                  <td>{{match.date}}</td>
                  <td><img src="{{match.home_team.image.url}}" class="img-fluid" alt=""> {{match.home_team}}</td>
                  <td><img src="{{match.visit_team.image.url}}" class="img-fluid" alt=""> {{match.visit_team}}</td>
                  <td>
                    {% if first_match %}
                      {% if forloop.first %}
                        {% if request.user.is_authenticated %}                                
                          {% if request.user.profile.is_trial or request.user.profile.is_subscribed %}
                            <a href="{% url 'match-detail' match.id %}" class="btn btn-primary">Pronosticos</a>
                          {% else %}
                            <a href="{% url 'checkout-session' %}" class="btn btn-primary">Suscríbete</a>
                          {% endif %}
                                      
                        {% else %}
                          <a href="{% url 'signup' %}" class="btn btn-primary">Regístrate</a>
                        {% endif %}
                      {% endif %}
                    {% else %}
                      {% if request.user.is_authenticated %}                                
                        {% if request.user.profile.is_trial or request.user.profile.is_subscribed %}
                          <a href="{% url 'match-detail' match.id %}" class="btn btn-primary">Pronosticos</a>
                        {% else %}
                          <a href="{% url 'checkout-session' %}" class="btn btn-primary">Suscríbete</a>
                        {% endif %}
                                  
                      {% else %}
                        <a href="{% url 'signup' %}" class="btn btn-primary">Regístrate</a>
                      {% endif %}
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      
    {% else %}
      <p style="color:red">No se encuentran partidos para las opciones seleccionadas. Prueba de nuevo.</p>
    {% endif %}
    
    </div>
  </div>
  
{% endblock %}

forecasts/templates/forecasts/matches_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Content Row -->
  <div class="row justify-content-center">
    <h1 class='mb-3 mt-3'>{{title}} {{match_list.0.league}}</h1>
    <div class="table-responsive">
      <table class="table mt-3">
        <thead>
            <tr>
              <th scope="col">Pais</th>
              <th scope="col">Liga</th>
              <th scope="col">Jornada</th>
              <th scope="col">Fecha</th>
              <th scope="col">Local</th>
              <th scope="col">Visitante</th>
              <th scope="col">Acción</th>
            </tr>
          </thead> 
          <tbody>
            {% for match in match_list %}
              <tr>
                <td><img src="{{match.league.contry.image.url}}" class="img-fluid" width=25px height=20px alt=""> </td>
                <td>{{match.league}}</td>
                <td>{{match.soccer_day}}</td>
                <td>{{match.date}}</td>
                <td><img src="{{match.home_team.image.url}}" class="img-fluid" alt=""> {{match.home_team}}</td>
                <td><img src="{{match.visit_team.image.url}}" class="img-fluid" alt=""> {{match.visit_team}}</td>
                <td>
                  
                  {% if first_match %}
                    {% if forloop.first %}
                      {% if request.user.is_authenticated %}                                
                        {% if profile.is_trial or profile.is_subscribed %}
                          <a href="{% url 'match-detail' match.id %}" class="btn btn-primary">Pronosticos</a>
                        {% else %}
                          <a href="{% url 'checkout-session' %}" class="btn btn-primary">Suscríbete</a>
                        {% endif %}                      
                      {% else %}
                        <a href="{% url 'signup' %}" class="btn btn-primary">Pronóstico</a>
                      {% endif %}
                    {% endif %}
                  {% else %}
                    {% if request.user.is_authenticated %}                                
                      {% if profile.is_trial or profile.is_subscribed %}
                        <a href="{% url 'match-detail' match.id %}" class="btn btn-primary">Pronosticos</a>
                      {% else %}
                        <a href="{% url 'checkout-session' %}" class="btn btn-primary">Suscríbete</a>
                      {% endif %}
                      
                    {% else %}
                      <a href="{% url 'signup' %}" class="btn btn-primary">Pronóstico</a>
                    {% endif %}
                  {% endif %}

                </td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="row mt-3 justify-content-center">
      {% include "core/cards_leagues.html" %}

  </div>
  </div>
  
{% endblock %}

forecasts/templates/forecasts/strategies_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Content Row -->
  <div class="row justify-content-center">
    
    <div class="container text-center">
      <div class="row ">
        <div class="col">
          <h1 class='mb-3 mt-3'>{{title}}</h1>
          <a href="{% url 'strategy-create' %}" class="btn btn-light">
            <img src="{% static 'core/img/nuevo.png' %}" class="img-fluid" title='Nueva estrategia'  width=40px height=40px alt="Nueva estrategia">
          </a>
        </div>
      </div>
    </div>
    <div class="col-md-6 mx-auto mb-5 mt-5 text-center shadow-lg p-3 mb-5 bg-body rounded">
      <div class="table-responsive">
        <table class="table mt-3">
          <thead>
              <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Acción</th>
              </tr>
            </thead> 
            <tbody>
              {% for strategy in strategy_list %}
                <tr>
                  <td>{{strategy.name}}</td>
                  
                  <td>
                    <a href="{% url 'strategy-update' strategy.id %}" class="btn btn-light">
                      <img src="{% static 'core/img/editar.png' %}" class="img-fluid" title='Editar estrategia' width=25px height=20px alt="Editar">
                    </a>
                    <a href="{% url 'strategy-delete' strategy.id %}" class="btn btn-light">
                      <img src="{% static 'core/img/papelera.png' %}" class="img-fluid" title='Eliminar estrategia' width=25px height=20px alt="Eliminar">
                    </a>
                  </td>
                </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  
{% endblock %}

forecasts/templates/forecasts/strategy_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
  <!-- Doctors Section -->
  
  <section id="doctors" class="doctors section">

    <!-- Section Title -->
    <div class="container section-title">
      <h2>{{title}}</h2>
    </div><!-- End Section Title -->
    <div class="container">
      <div class="row gy-4">
        <form method="post">{% csrf_token %}
            <p>¿Seguro que quieres eliminar la estrategia <strong>{{object.name}}</strong>?</p>
            
            <input type="submit" value="Confirmar" class="btn btn-success">
            <a href="{% url 'strategies-list' %}" class="btn btn-danger">Cancelar</a> 
        </form>
      </div>
    </div>
  </section><!-- /Doctors Section -->

{% endblock %}

forecasts/templates/forecasts/strategy_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col-12 text-center">
    <h1>{{title}}</h1>
  </div>
</div>
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.non_field_errors }}
    </div>
  {% endif %}

  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}

<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
  <div class="container" id="cont_strategy">
    <div class="row">
      <div class="col-md-8 mb-3 mt-3">
        {{form.name}}  
      </div>
    </div>
  </div>
  <div class="container text-center">
    <div class="row">
      <div class="col-md-6 mb-3 mt-3">
        <table class="table table-striped mt-3">
          <thead>
            <tr>
              <th scope="col">Mercado</th>
              <th scope="col">Desde (%)</th>
              <th scope="col">Hasta (%)</th>
            </tr>
          </thead> 
          <tbody>
            <tr>
              <td>Over 0.5 HT</td>
              <td>{{form.valor_ini_over_05_ht}}</td>
              <td>{{form.valor_fin_over_05_ht}}</td>
            </tr>
            <tr>
              <td>Over 1.5 HT</td>
              <td>{{form.valor_ini_over_15_ht}}</td>
              <td>{{form.valor_fin_over_15_ht}}</td>
            </tr>
            <tr>
              <td>Over 0.5 FT</td>
              <td>{{form.valor_ini_over_05_ft}}</td>
              <td>{{form.valor_fin_over_05_ft}}</td>
            </tr>
            <tr>
              <td>Over 1.5 FT</td>
              <td>{{form.valor_ini_over_15_ft}}</td>
              <td>{{form.valor_fin_over_15_ft}}</td>
            </tr>
            <tr>
              <td>Over 2.5 FT</td>
              <td>{{form.valor_ini_over_25_ft}}</td>
              <td>{{form.valor_fin_over_25_ft}}</td>
            </tr>
          </tbody>
        </table>
        <table class="table table-striped mt-3">
          <thead>
            <tr>
              <th scope="col">Mercado</th>
              <th scope="col">Desde (%)</th>
              <th scope="col">Hasta (%)</th>
            </tr>
          </thead> 
          <tbody>
            <tr>
              <td>Ambos Equipos Marcan</td>
              <td>{{form.valor_ini_aem}}</td>
              <td>{{form.valor_fin_aem}}</td>
            </tr>
          </tbody>
        </table>

        <table class="table table-striped mt-3">
          <thead>
            <tr>
              <th scope="col">Mercado</th>
              <th scope="col">Desde (%)</th>
              <th scope="col">Hasta (%)</th>
            </tr>
          </thead> 
          <tbody>
            <tr>
              <td>Local favorito</td>
              <td>{{form.valor_ini_local_favorito}}</td>
              <td>{{form.valor_fin_local_favorito}}</td>
            </tr>
            <tr>
              <td>Visitante favorito</td>
              <td>{{form.valor_ini_visitante_favorito}}</td>
              <td>{{form.valor_fin_visitante_favorito}}</td>
            </tr>
            
          </tbody>
        </table>


      </div>

      <div class="col-md-6 mb-3 mt-3">
        
        <table class="table table-striped mt-3">
          <thead>
            <tr>
              <th scope="col">Mercado</th>
              <th scope="col">Desde (%)</th>
              <th scope="col">Hasta (%)</th>
            </tr>
          </thead> 
          <tbody>
            <tr>
              <td>Local anota gol FT</td>
              <td>{{form.valor_ini_local_anota_ft}}</td>
              <td>{{form.valor_fin_local_anota_ft}}</td>
            </tr>
            <tr>
              <td>Local anota gol 1ª mitad</td>
              <td>{{form.valor_ini_local_anota_mitad_1}}</td>
              <td>{{form.valor_fin_local_anota_mitad_1}}</td>
            </tr>
            <tr>
              <td>Local anota gol 2ª mitad</td>
              <td>{{form.valor_ini_local_anota_mitad_2}}</td>
              <td>{{form.valor_fin_local_anota_mitad_2}}</td>
            </tr>
            <tr>
              <td>Visitante anota gol FT</td>
              <td>{{form.valor_ini_visitante_anota_ft}}</td>
              <td>{{form.valor_fin_visitante_anota_ft}}</td>
            </tr>
            <tr>
              <td>Visitante anota gol 1ª mitad</td>
              <td>{{form.valor_ini_visitante_anota_mitad_1}}</td>
              <td>{{form.valor_fin_visitante_anota_mitad_1}}</td>
            </tr>
            <tr>
              <td>Visitante anota gol 2ª mitad</td>
              <td>{{form.valor_ini_visitante_anota_mitad_2}}</td>
              <td>{{form.valor_fin_visitante_anota_mitad_2}}</td>
            </tr>
            <tr>
              <td>Local concede gol FT</td>
              <td>{{form.valor_ini_local_concede_ft}}</td>
              <td>{{form.valor_fin_local_concede_ft}}</td>
            </tr>
            <tr>
              <td>Local concede gol 1ª mitad</td>
              <td>{{form.valor_ini_local_concede_mitad_1}}</td>
              <td>{{form.valor_fin_local_concede_mitad_1}}</td>
            </tr>
            <tr>
              <td>Local concede gol 2ª mitad</td>
              <td>{{form.valor_ini_local_concede_mitad_2}}</td>
              <td>{{form.valor_fin_local_concede_mitad_2}}</td>
            </tr>
            <tr>
              <td>Visitante concede gol FT</td>
              <td>{{form.valor_ini_visitante_concede_ft}}</td>
              <td>{{form.valor_fin_visitante_concede_ft}}</td>
            </tr>
            <tr>
              <td>Visitante concede gol 1ª mitad</td>
              <td>{{form.valor_ini_visitante_concede_mitad_1}}</td>
              <td>{{form.valor_fin_visitante_concede_mitad_1}}</td>
            </tr>
            <tr>
              <td>Visitante concede gol 2ª mitad</td>
              <td>{{form.valor_ini_visitante_concede_mitad_2}}</td>
              <td>{{form.valor_fin_visitante_concede_mitad_2}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    
    <div class="row justify-content-center mb-3">
      <div class="col-md-6">
        {% if not object %}
          <input type="submit" class="btn btn-primary btn-block mt-3" value="Crear">
        {% else %}
          <input type="submit" class="btn btn-primary btn-block mt-3" value="Actualizar">
        {% endif %}
      </div>
    </div>
  </div>
</form>
{% endblock %}